package com.studenttribe.corejava.exception;

public class ExcepetionLogical {

	
	
	public static void divideNumbers(int a,String string) {
//        try {
//            int result = a / b; // Might throw ArithmeticException if b == 0
//            System.out.println("Result: " + result);
//        } catch (ArithmeticException e) {
//            System.out.println("Division by zero is not allowed.");
//        }
		System.out.println(a+string);
    }
	
  public static void main(String[] aa) {
	  
	  
	  System.out.println("samuhama erri pukualam ");
	  divideNumbers(10,"c");
	  System.out.println("samuhama erri pukualam ");
//	  try {
//		  int x =10;
//		  int y=20;
//		  System.out.println(x+y);
//		  int c= 10/0;
//	  }
//	  catch(Exception e){
//		  System.out.println("catched exception");
//	  }
//	  finally {
//		  System.out.println(10+20);
//	  }
	  
  }
	
}
